apiVersion: apps/v1
kind: Deployment
metadata:
  name: cee-v1-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: cee-v1-deployment
  template:
    metadata:
      labels:
        app: cee-v1-deployment
    spec:
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: nginx-volume
          configMap: 
            name: nginx-conf
      containers:
        - name: server
          image: nginx:1.19.3-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          volumeMounts:
            - name: nginx-volume
              mountPath: /etc/nginx/conf.d/

        - name: app
          image: docker.pkg.github.com/bruno-teksial/cee/cee:1.12
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URI
              value: mongodb://root:root@192.168.65.10:27017
            - name: DB_NAME
              value: cee
            - name: DB_COLLECTION
              value: db