apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: 
    server {
        root /var/www/html/public;
        
        location / {
            try_files $uri /index.php$is_args$args;
        }

        location ~ ^/index\.php(/|$) {
            fastcgi_pass localhost:9000;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $document_root;
            internal;
        }

        location ~ \.php$ {
            return 404;
        }

        error_log "/var/log/nginx/error.log" debug;
    }
