apiVersion: v1
kind: Service
metadata:
  name: cee-v1-service
spec:
  type: ClusterIP
  selector:
    app: cee-v1-deployment
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 80